#!/usr/bin/env php
<?php

use Dietercoopman\SajanPhp\DevPhpCommand;
use Dietercoopman\SajanPhp\DnsFlushCommand;
use Dietercoopman\SajanPhp\DnsUsingCommand;
use Dietercoopman\SajanPhp\IpLanCommand;
use Dietercoopman\SajanPhp\IpPublicCommand;
use Dietercoopman\SajanPhp\LaravelInstallCommand;
use Dietercoopman\SajanPhp\MiscSecretCommand;
use Dietercoopman\SajanPhp\SajanApplication;
use Dietercoopman\SajanPhp\StarCommand;
use Dietercoopman\SajanPhp\TipsCommand;
use Dietercoopman\SajanPhp\ToolsCheck;
use Dietercoopman\SajanPhp\ToolsInstall;
use Dietercoopman\SajanPhp\ToolsUpdate;
use Dietercoopman\SajanPhp\UpdateCommand;
use Dietercoopman\SajanPhp\WebpackInitCommand;
use Symfony\Component\Process\Process;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Start the console application.
 */
$version = trim(array_values(array_filter(explode('   ', Process::fromShellCommandline('composer global info | grep sajan')->mustRun()->getOutput())))[1]);

$app = new SajanApplication('<fg=green>Sajan</> version', $version, get_defined_vars()['argv']);
$app->add(new DevPhpCommand());
$app->add(new DnsFlushCommand());
$app->add(new DnsUsingCommand());
$app->add(new IpLanCommand());
$app->add(new IpPublicCommand());
$app->add(new LaravelInstallCommand());
$app->add(new MiscSecretCommand());
$app->add(new StarCommand());
$app->add(new TipsCommand());
$app->add(new ToolsInstall());
$app->add(new ToolsCheck());
$app->add(new ToolsUpdate());
$app->add(new UpdateCommand());
$app->add(new WebpackInitCommand());
$app->run();
