#!/usr/bin/env php
<?php

use Dietercoopman\SajanPhp\AliasCreateCommand;
use Dietercoopman\SajanPhp\AliasListCommand;
use Dietercoopman\SajanPhp\DnsFlushCommand;
use Dietercoopman\SajanPhp\DnsUsingCommand;
use Dietercoopman\SajanPhp\IpLanCommand;
use Dietercoopman\SajanPhp\IpPublicCommand;
use Dietercoopman\SajanPhp\OpenCommand;
use Dietercoopman\SajanPhp\SajanApplication;
use Dietercoopman\SajanPhp\SecretCommand;
use Dietercoopman\SajanPhp\SshKeyDirCommand;
use Dietercoopman\SajanPhp\SshKeyMakeCommand;
use Dietercoopman\SajanPhp\ToolsCheck;
use Dietercoopman\SajanPhp\ToolsInstall;
use Dietercoopman\SajanPhp\ToolsUpdate;
use Dietercoopman\SajanPhp\UpdateCommand;
use Dietercoopman\SajanPhp\WeatherCommand;
use Dietercoopman\SajanPhp\WebpackBuildCommand;
use Dietercoopman\SajanPhp\WebpackInitCommand;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

/**
 * Start the console application.
 */
$app = new SajanApplication('<fg=green>Sajan</> version', '2.0.10');
$app->add(new SecretCommand());
$app->add(new AliasListCommand());
$app->add(new AliasCreateCommand());
$app->add(new DnsFlushCommand());
$app->add(new DnsUsingCommand());
$app->add(new OpenCommand());
$app->add(new ToolsInstall());
$app->add(new ToolsCheck());
$app->add(new ToolsUpdate());
$app->add(new WeatherCommand());
$app->add(new IpPublicCommand());
$app->add(new IpLanCommand());
$app->add(new WebpackInitCommand());
$app->add(new WebpackBuildCommand());
$app->add(new UpdateCommand());
$app->run();